version: "3.9"
services:
  api:
    build: docker/
    ports:
      - "8082:8000"
    volumes:
      - ./src:/data
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*

networks:
  default:
    external: true
    name: yours
